apiVersion : apps/v1
kind: Deployment
metadata:
  name: "adf-b19a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "adf-b19a"
  template:
    metadata:
      labels:
        app: "adf-b19a"
    spec:
      containers:
        - name: "adf-b19a"
          image: "umgcacr.azurecr.io/adf"
          ports:
          - containerPort: 3389