apiVersion: v1
kind: Service
metadata:
    name: "adf-b19a"
    labels:
        app: "adf-b19a"
spec:
    type: LoadBalancer
    ports:
    - port: 3389
      targetPort: 3389
      protocol: TCP
      name: http
    selector:
        app: "adf-b19a"