apiVersion: v1
kind: Service
metadata:
    name: "adfaks-2715"
    labels:
        app: "adfaks-2715"
spec:
    type: LoadBalancer
    ports:
    - port: 3389
      targetPort: 3389
      protocol: TCP
      name: http
    selector:
        app: "adfaks-2715"