# This is a basic workflow to help you get started with Actions

name: Test Deploy ADF to Azure

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Azure Container Registry Build
        uses: ams0/acr-task-github-action@v2
        with:
          service_principal: $principal
          service_principal_password: $principal_password
          tenant: ${{ secrets.TENANT_ID }}
          registry: ${{ secrets.REGISTRY }}
          repository: $repository
          image: adf
          git_access_token: $git_access_token
          dockerfile: ./ADF/dockerfile
        env:
          principal: ${{ secrets.service_principal }}
          principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.TENANT_ID }}
          registry: ${{ secrets.REGISTRY }}
          repository: ${{ secrets.repository }}
          git_access_token: ${{ secrets.git_access_token }}

